// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOsthKiGp_MSLiwQzxiztxeq5U2tkE-EQ',
    appId: '1:558728977341:web:1b7019ab35575f216510d4',
    messagingSenderId: '558728977341',
    projectId: 'arfire-fe173',
    authDomain: 'arfire-fe173.firebaseapp.com',
    storageBucket: 'arfire-fe173.firebasestorage.app',
    measurementId: 'G-RN8D0FSVFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyO00jSLAKsdzFhqxFauxRq-xIVvUYKY',
    appId: '1:558728977341:android:adfa5f1d809c08a46510d4',
    messagingSenderId: '558728977341',
    projectId: 'arfire-fe173',
    storageBucket: 'arfire-fe173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6Zw7kf5H10szasmHvSrbkNvH6u6S9uM',
    appId: '1:558728977341:ios:19166306911c3ce96510d4',
    messagingSenderId: '558728977341',
    projectId: 'arfire-fe173',
    storageBucket: 'arfire-fe173.firebasestorage.app',
    iosBundleId: 'com.example.arCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6Zw7kf5H10szasmHvSrbkNvH6u6S9uM',
    appId: '1:558728977341:ios:19166306911c3ce96510d4',
    messagingSenderId: '558728977341',
    projectId: 'arfire-fe173',
    storageBucket: 'arfire-fe173.firebasestorage.app',
    iosBundleId: 'com.example.arCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOsthKiGp_MSLiwQzxiztxeq5U2tkE-EQ',
    appId: '1:558728977341:web:76568e6d50b5b4936510d4',
    messagingSenderId: '558728977341',
    projectId: 'arfire-fe173',
    authDomain: 'arfire-fe173.firebaseapp.com',
    storageBucket: 'arfire-fe173.firebasestorage.app',
    measurementId: 'G-DRY09EGJ0D',
  );
}
